name:                whisper
version:             0.1.0.0
github:              "pacokwon/whisper"
license:             MIT
author:              "pacokwon"
maintainer:          "haechank@gmail.com"
copyright:           "2023 Paco Kwon"

extra-source-files:
- README.md

description: A Simple Lisp Interpreter in Haskell

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.4
- text >= 2.0
- containers
- mtl
- transformers
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  whisper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whisper
  alt-exe:
    main:                alt.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whisper
